export const ForwardSkipReason = {
  NO_LINKS: "NO_LINKS",
  NO_ACTIVE_ROUTES: "NO_ACTIVE_ROUTES",
  SESSION_DISCONNECTED: "SESSION_DISCONNECTED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
  DUPLICATE_FORWARD: "DUPLICATE_FORWARD",
  ML_GENERATION_FAILED: "ML_GENERATION_FAILED",
  AMAZON_GENERATION_FAILED: "AMAZON_GENERATION_FAILED",
  AFFILIATE_CREDENTIAL_MISSING: "AFFILIATE_CREDENTIAL_MISSING",
  MEDIA_DOWNLOAD_FAILED: "MEDIA_DOWNLOAD_FAILED",
  MEDIA_SEND_FALLBACK: "MEDIA_SEND_FALLBACK",
  SEND_FAILED: "SEND_FAILED",
  FROM_ME: "FROM_ME",
  PRIVATE_CHAT: "PRIVATE_CHAT",
  REACTION: "REACTION",
  PROTOCOL: "PROTOCOL",
  MISSING_REMOTE_JID: "MISSING_REMOTE_JID",
  MISSING_MESSAGE_ID: "MISSING_MESSAGE_ID",
} as const;

export type ForwardSkipReason =
  (typeof ForwardSkipReason)[keyof typeof ForwardSkipReason];
